---
title: "R tools for a code-based data workflow"
output: 
  bookdown::pdf_document2:
    toc: true
    number_sections: false

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Webinar Information

## Description  
After a brief review of the advantages of a code-based workflow for ecological survey data, we introduce participants to some useful tools available via the R programming language for moving data along the data life cycle. We suggest some accessible tools in R for each step of the life cycle, and conclude with a walk through of how the functionality available in R can increase the reliability, efficiency, and transparency of scientific data management.

## Presenters    
- [McCrea Cobb](mailto:mccrea_cobb@fws.gov) (Refuge Inventory and Monitoring Program, Alaska) and [Adam Smith](mailto:d_smith@fws.gov) (Refuge Inventory and Monitoring Program, Legacy FWS Region )

## When
June 24, 2020 (3:00-4:30 EST)

## Location  
[Webinar link]()

## Additional resources
[GitHub repository](https://github.com/USFWS/data-mgt-with-r)


# Outline

## Introduction (*McCrea, 5 min*)
  + Data life cycle review 
  + Manual versus code-based workflow
    + The manual data workflow
      + Example
      + Limitations
    + The code-based data workflow
      + Advantages
        + Documented
        + Reproducible
        + Replicable
        + More efficient
        + Less error-prone
        
## Planning (*McCrea, 10 min*)
  + Make an R project self contained and portable
    + File directory structure
    + Relative paths
  + Dependency management
    + packrat
    + containers (docker)
   + Standardize file naming convention
  + Organizing R files (Numeric preface in the names of ordered scripts)
  + Recommended RStudio settings
     + E.g., Uncheck "restore .RData into workspace at startup"
  + Version control
     + Storing versions
     + Collaboration
     
## Documenting (*Adam, 10 min*)
  + rOxygen 
  + R documentation file
  + Code commenting
  
## Acquiring (*Adam, 5 min*)
  + local and remote
  + querying data
    + AGOL
    + iNaturalist
    + PRIMR web services
    + SQL query: IRIS warehouse
    
## Processing and Analyzing (*Adam, 15 min*)
   + Getting data into R
  + QC
  + Tidying data
  + Visualizing
   + EDA
   
## Sharing (*McCrea, 10 min*)
  + Reporting
    + RMarkdown
       + Bat reporting for mobile aucistics
     + Dashboards
      + COVID 19 example
    + Shiny apps
       + collarviewer
       + power analysis for butterfly surveys
       
## Archiving (*McCrea, 10 min*)
   + Saving results to ServCat or some other data repository

## An example R project / Live demo (*10 min*)

## Questions (*10 min*)


# Resources (Links)

**Introduction to R**

- [An Introduction to R book](https://intro2r.com/)
- [R for Excel Users](https://rstudio-conf-2020.github.io/r-for-excel/)

**Resources for Teaching R**  

- [DataCamp's tidyverse course](https://learn.datacamp.com/courses/working-with-data-in-the-tidyverse)
- [learnr package](https://rstudio.github.io/learnr/)
- [RStudio teaching resources](https://education.rstudio.com/teach/materials/)
- [Data Wrangling, Exploration and Analysis with R "STAT 545"](https://stat545.com/)


**R Resources**

- [Why learn R](https://datacarpentry.org/R-ecology-lesson/00-before-we-start.html#r_code_is_great_for_reproducibility)
- [What they forgot to teach you about R](https://rstats.wtf/)
- [R cheatsheets](https://rstudio.com/resources/cheatsheets/)
- [Project-oriented workflow](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/)


**Style Guides**
- [Tidyverse style guide](https://style.tidyverse.org/)
- [DataNovia R style guide](https://www.datanovia.com/en/blog/r-coding-style-best-practices/)


**R Packages**

- [Packaging your reproducible analysis](https://thomasleeper.com/2016/11/analysis-as-package/)
- [R packages](http://r-pkgs.had.co.nz/)
- [Packaging data analytical work reproducibly using R (and friends)](https://peerj.com/preprints/3192.pdf)


**Project management**

- [Stop working directory insanity!](https://gist.github.com/jennybc/362f52446fe1ebc4c49f)
- [A minimal project tree in R](https://talesofr.wordpress.com/2017/12/12/a-minimal-project-tree-in-r/)
- [Organizing the project directory](https://nicercode.github.io/blog/2013-05-17-organising-my-project/)
- [Designing projects](https://nicercode.github.io/blog/2013-04-05-projects/)
- [Project management with RStudio](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/)
- [File structure for data management](https://r-dir.com/blog/2013/11/folder-structure-for-data-analysis.html)
- [Organizing files for data analysis](https://github.com/AndersenLab/IBiS-Bootcamp/wiki/Organizing-files-for-data-analysis)
- [A meaningful file structure for R projects](https://www.r-bloggers.com/a-meaningful-file-structure-for-r-projects/)
- [An introduction to Docker for R users](https://colinfay.me/docker-r-reproducibility/)


**Project Directory Templates**

- [MakeProject package](https://cran.r-project.org/web/packages/makeProject/index.html)
- [rrtools package](https://github.com/benmarwick/rrtools)
- [prodigenr package](https://cran.r-project.org/web/packages/prodigenr/readme/README.html)


**General Coding Best Practices**

- [What's in a name? The concepts and language of replication and reproducibility](https://thomasleeper.com/2015/05/open-science-language/)
- [Best practices for scientific computing](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)
- [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
- [Ten simple rules for documenting scientific software](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006561)

**Version Control**  

- [Happy Git with R](https://happygitwithr.com/)


**Other**

- [How to share your data with a statistician](https://github.com/jtleek/datasharing)
- [Tools for reproducible research](http://kbroman.org/Tools4RR/assets/lectures/06_org_eda_withnotes.pdf)
- [Reproducibility vs. replicability: a brief history of a confused terminology](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5778115/)