---
title: "Planning Notes"
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 5/7/2020 Call

## Agenda

### What is the take-home message from the webinar? You can (and should) use R entirely for your data workflow? 
- Demonstate how R can be used for the data life cycle process
- A good clear demo of this.
- Show the endpoint first. The pie in the sky.
    - Example: SppDistMonProj, mobile aucistic recorder package
        
### How do we want to collaborate on this? Through GitHub? If so, how? Separate branches or forked?
- We will use GitHub
- McCrea will work off master branch, Adam will fork
- We will try to keep work distinct in the repo (create seperate RMarkdown presentations and merge if needed when they are completed.

### Do we want to use the SppDistMonProj package as the example? What other examples do we have?
- SppDistMonProj is a good example, but we will look for others and make a decision on it during our next meeting on 5/13.

### Should we attempt to include any class participation? If so, what format?
- Probably not enough time.

### Version control?
- We will mention it without going into any detail on it's use
- Repo is available for the webinar, we can then mention GitHub and version control

### Presentation slide file format?
- RMarkdown
- Flipbook is pretty cool tool for incrementally describing code. Could be used if we use xaringan formatted RMarkdown slides.

## Action Items
- McCrea: send project file dir template to Adam
- McCrea: send RMarkdown presentation template to Adam
- All: look for other project examples and be ready to make a final decision on 5/13
- All: look for other R training tools and materials
- McCrea: Contact Brent Frakes re: writing files to product records in ServCat
- Adam: look into accessing Survey123 data using R


# 5/13/2020 Call

## Agenda

### Make a decision on the project example(s)


### Discuss how to divide the materials


### Decide on how to present the materials


## Action Items


